moysklad/api-remap-1.2-doc

- source/includes/_notification.md
Убрано поле uuidhref из примеров уведомлений
> MC-30631 убрано поле uuidhref из примеров уведомлений

- source/includes/_audit.md
> MC-30103 update Audit add new AuditEventType + Filter

- source/includes/_country.md
Добавлен uuidHref в метаописание для сущности Country
> MC-30060 Country uuidHref

- source/includes/_report_sales_orders.md
> MC-32892 fix

- source/includes/_notification.md
Удаление звонков из настроек уведомлений
> MC-32547 Удаление звонков из настроек уведомлений

- source/includes/_general.md
> MC-33595 fix mistake

- source/includes/_bundle.md
- source/includes/_product.md
- source/includes/_productFolder.md
- source/includes/_service.md
> MC-34622 Tax system same as group

- source/includes/_bundle.md
- source/includes/_product.md
- source/includes/_service.md
- source/includes/_variant.md
> MC-32189 fix examples

- source/includes/_retailstore.md
> MC-38924 add fiscalValidityDate in retailStore

- source/includes/_general.md
> MC-41272 add information about deprecated versions

- CHANGELOG.md
- source/includes/_changelog.md
- source/includes/_productFolder.md
> MC-41897 productFolder description fix

- CHANGELOG.md
- source/includes/_autofill.md
- source/includes/_changelog.md
> MC-39453 add evaluation of cost to Wizard endpoint

- source/includes/_assortment.md
- source/includes/_counterparty.md
- source/includes/_report_stock.md
- source/includes/_retaildemand.md
- source/includes/_retailstore.md
- source/includes/_usersettings.md
> MC-43238 change localhost on online.moysklad.ru

- CHANGELOG.md
- source/includes/_changelog.md
- source/includes/_retailstore.md
> MC-43311 fix qrBankPercent type mistake

- CHANGELOG.md
- source/includes/_changelog.md
- source/includes/_product.md
- source/includes/_productFolder.md
> MC-43686 fix wrong http method in product folder

- CHANGELOG.md
- source/includes/_general.md
- source/includes/changelog/_changelog.md
> MC-44461 fix broken urls

- CHANGELOG.md
- source/includes/changelog/_changelog.md
- source/includes/dictionaries/_variant.md
> MC-44738 fix mistake in example

- source/includes/dictionaries/_bundle.md
- source/includes/dictionaries/_service.md
- source/includes/dictionaries/_variant.md
> MC-44174 change types

- source/includes/documents/_customerOrder.md
> MC-44266 add reservedSum

- source/includes/_general.md
> MC-46000 change description additional field

- CHANGELOG.md
- source/includes/dictionaries/_retailstore.md
> MC-47545 changed description for markingSellingMode

- CHANGELOG.md
> MC-47641 deleted duplicate in CHANGELOG.md

- config.rb
Включил плагин assets_hask в конфиге middleman - это заставит middleman при пересборке добавлять к имени asset'а хеш его содержимого. Что заставит браузер загружать новый asset независимо от своих локальных настроек кеша.
> MC-65720 set cache busting strategy
